[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending_protocol = "AymeZTGqtjkaHVhDCpdfby1G9YkTn8EMPSQMRdGVjJSA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[build]
args = ["--bpf-version", "1"]