export const errors =
{
  notCEOErrorMsg: "Only the CEO can call this function",
  notSolvencyTreasurerErrorMsg: "Only the Solvency Treasurer can call this function",
  notLiquidationTreasurerErrorMsg: "Only the Liquidation Treasurer can call this function",
  notPriceOracle: "Only the Price Oracle can call this function",
  solvencyInsuranceFeeOnInterestEarnedRateTooHighErrorMsg: "The solvency insurance fee on interest earned rate can't be greater than 4%",
  outOfRangeError: "ERR_OUT_OF_RANGE",
  subMarketFeeOnInterestEarnedRateTooHighErrorMsg: "The Sub Market fee on interest earned rate can't be greater than 100%",
  subMarketOwnerLookUpTableMissingErrorMsg: "You must include a Look Up Table Address when a user creates their first Sub Market",
  globalLimitExceededErrorMsg: "You can't deposit more than the global limit",
  expectedThisAccountToExistErrorMsg: "The program expected this account to be already initialized",
  insufficientFundsErrorMsg: "You can't withdraw more funds than you've deposited",
  ataDoesNotExistErrorMsg: "failed to get token account balance: Account ",
  debtExceeding70PercentOfCollateralErrorMsg: "You can't withdraw or borrow an amount that would cause your borrow liabilities to exceed 70% of deposited collateral",
  insufficientLiquidityErrorMsg: "Not enough liquidity in the Token Reserve for this withdraw or borrow",
  notLiquidatableErrorMsg: "You can't liquidate an account whose borrow liabilities aren't 80% or more of their deposited collateral",
  overLiquidationErrorMsg: "You can't repay more than 50% of a liquidati's debt position",
  notInsolventErrorMsg: "You can't zero out an account whose borrow liabilities aren't 100% or more of their deposited collateral",
  tooManyFundsErrorMsg: "You can't pay back more funds than you've borrowed",
  griefingErrorMsg: "You must repay atleast 10% of the borrow position if the account is in an unhealthy state. This prevents 'griefing'",
  incorrectOrderOfTabAccountsErrorMsg: "You must provide the sub user's tab accounts ordered by user_tab_account_index",
  accountNameTooLongErrorMsg: "Lending User Account name can't be longer than 25 characters",
  unexpectedTabAccountErrorMsg: "Unexpected Tab Account PDA detected",
  missingExpectedTokenReserveErrorMsg: "Expected Token Reserve missing for user refresh",
  unexpectedSubMarketErrorMsg: "Unexpected SubMarket Account PDA detected",
  unexpectedMonthlyStatementErrorMsg: "Unexpected Monthly Statement Account PDA detected",
  notFeeCollectorErrorMsg: "Only the Fee Collector can claim the fees",
  staleTokenReserveOrLendingUserErrorMsg: "Token Reserve or lending user health data was stale",
  oraclePriceNotFoundErrorMsg: "Oracle price not found",
  invalidOracleSignatureErrorMsg: "This price wasn't signed by the Oracle"
}